server {

    listen [::]:443 ssl;
    listen 443 ssl;

    ssl_certificate /etc/ssl/qycli.crt;
    ssl_certificate_key /etc/ssl/qycli.key;

    include /var/www/dmn.tld/conf/or/*.conf; # server_name can be found there

    #access_log /var/log/openresty/dmn.tld.access.log;
    error_log /var/log/openresty/dmn.tld.error.log;

    #add_header Cache-Control "public, stale-while-revalidate=60s";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    
    include common/wpsuperpagecache.conf;
    #include common/wpfcgi.conf;
    include common/wpcommon.conf;

    location LOCATION {
        proxy_pass http://[::1]:8088/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}