[qycli]
user = unyphp
group = unyweb

ping.path = /ping

pm = static
pm.max_children = 2
pm.status_path = /status
pm.max_requests = 512

request_terminate_timeout = 900

chdir = /
prefix = /run/php/ver
listen = php-fpm.sock
listen.owner = unyweb
listen.group = unyweb
listen.mode = 0660
listen.backlog = 32768

catch_workers_output = yes
