#!/bin/bash
# shellcheck disable=1091,2016

[[ $(whoami) != "root" ]] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

## Install qycli and stack with "wget -qO- qyc.li/inst | bash" or the dev version with "wget qyc.li/inst && bash inst v dev"
## or "bash <(wget -qO- qyc.li/inst) v dev k no phpv 7.4"

## Optimize the host if you are not in a container with "wget -qO- qyc.li/kernel | bash"

inst_qycli() {
    [[ -f /usr/local/bin/qyc ]] && echo "qycli is already installed, stopping the process. Just type qyc to get the help message or go to qycli.org to learn." && exit
    [[ ! -d /var/qyc ]] && mkdir -p /var/qyc/{qycli,cloudflare/{dns,crowdsec},sites,cache/git,bin}
    tee /var/qyc/cnf.yaml <<EOF
branch_name: $branch_name
sec_install: $sec_install
php_version: $php_version
cloudflare_token: $cloudflare_token
auto_update: $auto_update
EOF

    if command -v wget >/dev/null; then
        echo "Installing unypkg - https://unypkg.org"
        wget -qO- uny.nu/pkg
    else
        echo "wget not found, aborting."
        exit
    fi

    if [[ $cloudflare_token == "" ]]; then
        echo "You need to supply a Clouflare API token with the permission template 'Create Additional Tokens'."
        echo "Then you supply it to the qycli installation like this: wget -qO- qyc.li/inst | bash -s cft YOURTOKENHERE"
    else
        printf "\nGetting Cloudflare data.\n\n"
        upd_get_cf_tokens
        upd_get_cf_accounts_and_zones
    fi

    if ! command -v git >/dev/null; then
        unyp install git
        unyp system-install git
    fi

    git -C /var/qyc/qycli clone -b "$branch_name" https://github.com/HOSTYON/qycli .
    git -C /var/qyc clone -b "$branch_name" https://github.com/HOSTYON/qycli-plugin

    ln -sfv /var/qyc/qycli/bin/qyc /bin/qyc
    chmod 755 /bin/qyc

    source /var/qyc/qycli/bin/stk
    source /var/qyc/qycli/bin/help
    source /var/qyc/qycli/bin/upd
    printf "\nqycli (%s) was installed.\n\n" "$branch_name"

    printf "\nInstalling the qycli stack now.\n\n"
    stk_install

    if [[ "$kernel_tweaks" == "yes" ]]; then
        printf "\nOptimizing kernel configurations. You should restart after the full installation has finished.\n\n"
        source /var/qyc/qycli/kernel
    fi
    if [[ "$sec_install" == "yes" ]]; then
        printf "\nSecuring the network. Only SSH and Cloudflare connections will be allowed.\n\n"
        source /var/qyc/qycli/sec_firewall
    fi

    upd_system_resources_qycli_cnf
    printf "\nqycli was installed.\n\n"
}

branch_name=stable
sec_install=no
kernel_tweaks=yes
php_version=8.1
auto_update=no

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    v | version)
        if [[ "$2" == "beta" ]]; then
            branch_name=beta
        elif [[ "$2" == "dev" ]]; then
            branch_name=dev
        else
            echo "$2 is not a valid qycli version. Aborting."
            exit
        fi
        shift
        ;;
    s | sec | security)
        if [[ "$2" =~ ^(n|no)$ ]]; then
            sec_install=yes
        fi
        shift
        ;;
    k | kernel | tweaks)
        if [[ "$2" =~ ^(n|no)$ ]]; then
            kernel_tweaks=no
        fi
        shift
        ;;
    php | phpv | php-version)
        if [[ "$2" =~ ^(7.4|8.1|8.2|8.3)$ ]]; then
            php_version=$2
        else
            echo 'Not supported PHP version, try again with "7.4", "8.1", "8.2" or "8.3". Exiting.'
            exit
        fi
        shift
        ;;
    cft | cloudflare-token)
        cloudflare_token=$2
        shift
        ;;
    aupd | autoupd | autoupdate)
        auto_update=$2
        shift
        ;;
    esac
    shift
done

inst_qycli
