#!/bin/bash

[[ $(whoami) != "root" ]] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

## Install qycli and stack with "wget -qO- qyc.li/inst | bash" or the dev version with "wget qyc.li/inst && bash inst v dev"
## or "bash <(wget -qO- qyc.li/inst) v dev k no phpv 7.4"

## Optimize the host if you are not in a container with "wget -qO- qyc.li/kernel | bash"

inst_qycli() {
    [[ -f /usr/local/bin/qyc ]] && echo "qycli is already installed, stopping the process. Just type qyc to get the help message or go to qycli.org to learn." && exit
    [[ ! -d /var/qyc ]] && mkdir -p /var/qyc/{qycli,cloudflare/{dns,crowdsec},sites,cache/git,bin}
    tee /var/qyc/cnf.yaml <<EOF
branch_name: $branch_name
sec_install: $sec_install
php_version: $php_version
cloudflare_token: $cloudflare_token
auto_update: $auto_update
nginx_source: $nginx_source
php_source: $php_source
EOF

    apt update && apt -y install git
    git config --global submodule.recurse true

    git -C /var/qyc/qycli clone -b "$branch_name" https://github.com/HOSTYON/qycli .
    git -C /var/qyc clone https://github.com/HOSTYON/qycli-plugin

    #git -C /var/qyc/qycli-plugin submodule update --init --recursive
    cp /var/qyc/qycli/bin/qyc /usr/bin/qyc
    chmod 755 /usr/bin/qyc
    #chmod 755 /var/qyc/qycli/kernel
    #chmod 755 /var/qyc/qycli/sec_firewall
    # shellcheck disable=1091
    source /var/qyc/qycli/bin/stk
    # shellcheck disable=1091
    source /var/qyc/qycli/bin/help
    # shellcheck disable=1091
    source /var/qyc/qycli/bin/upd
    printf "\nqycli (%s) was installed.\n\n" "$branch_name"

    printf "\nInstalling the qycli stack now.\n\n"
    stk_install

    if [[ "$kernel_tweaks" == "yes" ]]; then
        printf "\nOptimizing kernel configurations. You should restart after the full installation has finished.\n\n"
        # shellcheck disable=1091
        source /var/qyc/qycli/kernel
    fi
    if [[ "$sec_install" == "yes" ]]; then
        printf "\nSecuring the network. Only SSH and Cloudflare connections will be allowed.\n\n"
        # shellcheck disable=1091
        source /var/qyc/qycli/sec_firewall
    fi
    if [[ $cloudflare_token != "" ]]; then
        printf "\nGetting Cloudflare data.\n\n"
        upd_get_cf_token_accounts_and_zones
        upd_get_cf_accounts_and_zones
    fi

    upd_system_resources_qycli_cnf
    printf "\nqycli was installed.\n\n"
}

branch_name=stable
sec_install=no
kernel_tweaks=yes
php_version=8.1
auto_update=no
# shellcheck disable=2016
nginx_source='"https://github.com/HOSTYON/qycli-nginx/releases/download/\"$nginx_release_tag\"/qycli-nginx.tar.xz"'
# shellcheck disable=2016
php_source='"https://github.com/HOSTYON/qycli-php\"$php_version_short\"/releases/download/\"$php_release_tag\"/qycli-php\"$php_version_short\".tar.xz"'

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    v | version)
        if [[ "$2" == "beta" ]]; then
            branch_name=beta
        elif [[ "$2" == "dev" ]]; then
            branch_name=dev
        fi
        shift
        ;;
    s | sec | security)
        if [[ "$2" =~ ^(n|no)$ ]]; then
            sec_install=yes
        fi
        shift
        ;;
    k | kernel | tweaks)
        if [[ "$2" =~ ^(n|no)$ ]]; then
            kernel_tweaks=no
        fi
        shift
        ;;
    php | phpv | php-version)
        if [[ "$2" =~ ^(7.4|8.0|8.1|8.2)$ ]]; then
            php_version=$2
        else
            echo 'Not supported PHP version, try again with "7.4", "8.0" or "8.1". Exiting.'
            exit
        fi
        shift
        ;;
    cft | cloudflare-token)
        cloudflare_token=$2
        shift
        ;;
    aupd | autoupd | autoupdate)
        auto_update=$2
        shift
        ;;
    esac
    shift
done

inst_qycli
