#!/bin/bash

# Make sure system is up to date
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y

## Install WordPress Stack

# Install NGINX
sudo apt -y install curl gnupg2 ca-certificates lsb-release
echo "deb http://nginx.org/packages/mainline/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
sudo apt update && sudo apt install nginx








if [[ $1 == "testarg" ]]; then
    echo "test arg worked"
    else
    echo "no argument passed but script ran"
fi

