#!/bin/bash

# Variables
phpv=7.4 # Newest PHP Version

# Make sure system is up to date
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y

## Install LEMP Stack - NGINX, MariaDB, PHP-FPM
# Install NGINX
sudo apt -y install curl gnupg2 ca-certificates lsb-release
echo "deb http://nginx.org/packages/mainline/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
sudo apt update && sudo apt install nginx

# Install newest MariaDB
sudo apt -y install apt-transport-https
curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash -s -- --skip-maxscale
sudo apt -y install mariadb-server

# Install newest stable PHP
sudo apt -y install php${phpv}-bcmath php${phpv}-common php${phpv}-curl php${phpv}-fpm php${phpv}-gd php${phpv}-imagick \
php${phpv}-mbstring php${phpv}-mysql php${ver}-redis php${phpv}-soap php${phpv}-xml php${phpv}-zip

# Install Redis with Snap
sudo fuser -vki /var/lib/dpkg/lock
sudo apt purge snapd
sudo dpkg --configure -a
sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade
sudo apt install snapd -y
sleep 2 && sudo snap set system refresh.timer=1:00-4:00 && sleep 1
sudo snap install redis






if [[ $1 == "testarg" ]]; then
    echo "test arg worked"
    else
    echo "no argument passed but script ran"
fi

