#!/bin/bash

# Security for qycli

[[ $(whoami) != "root" ]] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

apt update && apt -y install ufw

[[ ! -d /var/opt/qycli ]] && mkdir /var/opt/qycli
curl -s https://www.cloudflare.com/ips-v4 -o /var/opt/qycli/cloudflare_ipv4_ips
curl -s https://www.cloudflare.com/ips-v6 -o /var/opt/qycli/cloudflare_ipv6_ips

ssh_port=$(grep -w "Port" -i /etc/ssh/sshd_config | sed s+'.*Port '++)

if [[ "$(ufw status | grep "Status:" | sed s+"Status: "++)" == "active" ]]; then
    ufw --force disable
    ufw --force reset
fi

ufw default allow outgoing
ufw default deny incoming

ufw allow proto tcp from $ssh_port

#for cfip in `cat /var/opt/qycli/cloudflare_ipv4_ips`; do ufw allow proto tcp from $cfip to any port 443 comment 'Cloudflare IP'; done
for cfip in `cat /var/opt/qycli/cloudflare_ipv6_ips`; do ufw allow proto tcp from $cfip to any port 443 comment 'Cloudflare IP'; done

echo "y" | ufw enable

