#!/bin/bash

# Firewall for qycli

[[ $(whoami) != "root" ]] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

[[ ! $(command -v ufw) ]] && apt update && apt -y install ufw

[[ ! -d /var/opt/qycli ]] && mkdir /var/opt/qycli
curl -s https://www.cloudflare.com/ips-v4 -o /var/opt/qycli/cloudflare_ipv4_ips
curl -s https://www.cloudflare.com/ips-v6 -o /var/opt/qycli/cloudflare_ipv6_ips

ufw --force disable
ufw --force reset
ufw default allow outgoing
ufw default deny incoming

# Allowing SSH
ssh_port=$(grep -w "Port" -i /etc/ssh/sshd_config | sed s+'.*Port '++)
ufw allow $ssh_port/tcp

# Allowing HTTPS over IPv6 only
#for cfip in `cat /var/opt/qycli/cloudflare_ipv4_ips`; do ufw allow proto tcp from $cfip to any port 443 comment 'Cloudflare IP'; done
for cfip in $(cat /var/opt/qycli/cloudflare_ipv6_ips)
do
    ufw allow proto tcp from $cfip to any port 443 comment 'Cloudflare IP'
done

# Using Cloudflare for DNS
ufw allow from 2606:4700:4700::1111 to any port 53 comment 'Cloudflare DNS IP'
ufw allow from 2606:4700:4700::1001 to any port 53 comment 'Cloudflare DNS IP'
ufw allow from 1.1.1.1 to any port 53 comment 'Cloudflare DNS IP'
ufw allow from 1.0.0.1 to any port 53 comment 'Cloudflare DNS IP'
ufw allow proto tcp from $cfip to any port 443 comment 'Cloudflare IP'
sed '0,/.*DNS.*/s++DNS=2606:4700:4700::1111 2606:4700:4700::1001+' -i /etc/systemd/resolved.conf
sed '0,/.*FallbackDNS.*/s++FallbackDNS=1.1.1.1 1.0.0.1+' -i /etc/systemd/resolved.conf
systemctl restart systemd-resolved

# Using Cloudflare for NTP
for timeip in $(dig AAAA time.cloudflare.com +short && dig time.cloudflare.com +short)
do
    ufw allow from $timeip to any port 123 comment 'Cloudflare Time IP'
done

sed '0,/.*NTP.*/s++NTP=time.cloudflare.com+' -i /etc/systemd/timesyncd.conf
systemctl restart systemd-timesyncd

# Enable the Firewall
echo "y" | ufw enable