#!/bin/bash

# Firewall for qycli

# Check if I am root
[[ $(whoami) != "root" ]] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit
# Check if there is SSH
[[ ! $(systemctl status ssh) ]] && echo "No SSH service found, aborting..." && exit
# Check if there is netplan
[[ ! $(command -v netplan) || ! $(find /etc/netplan -type f -printf "%f\n" | sort -r | head -n1) ]] && echo "Netplan not found, aborting..." && exit

[[ $(command -v ufw) ]] && echo "Found UFW, purging it." && apt -y purge ufw
[[ $(command -v firewall-cmd) ]] && echo "Found firewalld, purging it." && apt -y purge firewalld
[[ ! $(command -v nft) ]] && echo "Didn't find nftables, installing it." && apt update && apt -y install nftables && systemctl enable nftables.service

# Determine SSH port of host
activesshport=$(systemctl status ssh | grep -Po "(?<=port ).*(?=\.)" | sort -u)
confsshport=$(grep -Po "(?<=^Port ).*" /etc/ssh/sshd_config)
if [[ $activesshport != "$confsshport" ]]; then
    sed -i.bk 's/#Port/Port/g' /etc/ssh/sshd_config
    sed -i "s/Port *[0-9]*/Port $activesshport/g" /etc/ssh/sshd_config
    systemctl restart sshd
    sshport="$activesshport"
else
    sshport="$activesshport"
fi

tee /etc/nftables.conf >/dev/null <<EOF
#!/usr/sbin/nft -f

flush ruleset

table inet filter {
        chain input {
                # By default, drop all traffic unless it meets a filter
                # criteria specified by the rules that follow below.
                type filter hook input priority 0; policy drop;
                ct state invalid counter drop comment "early drop of invalid packets"
                ct state {established, related} counter accept comment "accept all connections related to connections made by us"
                iif lo accept comment "accept loopback"
                iif != lo ip daddr 127.0.0.1/8 counter drop comment "drop connections to loopback not coming from loopback"
                iif != lo ip6 daddr ::1/128 counter drop comment "drop connections to loopback not coming from loopback"
                ip protocol icmp counter accept comment "accept all ICMP types"
                ip6 nexthdr icmpv6 counter accept comment "accept all ICMP types"

                # Allow SSH
                tcp dport { $sshport } accept

                # Allow only HTTPS from Cloudflare
        }
        chain forward {
                type filter hook forward priority 0; policy drop;
        }
        chain output {
                type filter hook output priority 0; policy accept;
        }
}
EOF

while IFS= read -r cfip; do
    sed "/# Allow only HTTPS from Cloudflare/a\                ip6 saddr $cfip tcp dport { 443, 80 } accept # Cloudflare IP" -i /etc/nftables.conf
done </var/qyc/cache/cloudflare_ipv6_ips_new
while IFS= read -r cfip; do
    sed "/# Allow only HTTPS from Cloudflare/a\                ip saddr $cfip tcp dport { 443, 80 } accept # Cloudflare IP" -i /etc/nftables.conf
done </var/qyc/cache/cloudflare_ipv4_ips_new

nft -f /etc/nftables.conf
systemctl enable nftables
systemctl restart crowdsec-firewall-bouncer

# Use Cloudflare for time sync
sed '0,/.*NTP.*/s++NTP=time.cloudflare.com+' -i /etc/systemd/timesyncd.conf
systemctl restart systemd-timesyncd

printf "\nFirewall installed.\n\n"
