location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

location ~ [^/]\.php(/|$) {
    # Isolate the script name cleanly
    include common/php-fpm.conf;

    # Upstream Processing Track
    fastcgi_pass phpMICROVER-fpm;
}
