#!/usr/bin/env sh
# shellcheck disable=1091,2016

branch_name=dev

# Run installer with options
wget -q https://raw.githubusercontent.com/HOSTYON/qycli/refs/heads/"$branch_name"/ins/inst
chmod +x inst
. inst
rm -f inst
