#!/usr/bin/env sh
# shellcheck disable=1091,2016

branch_name=dev

if [ -p /dev/stdin ]; then
    echo "You piped something to this script!"
    echo "Some output of the command you piped:"
    read input
    echo "$input"
    echo "That was all."
    pipe=true
else
    echo "No input piped to script."
fi

# Run installer with options
#wget -q https://raw.githubusercontent.com/HOSTYON/qycli/refs/heads/"$branch_name"/ins/inst
#. inst
#rm -f inst
