#!/usr/bin/env sh
# shellcheck disable=1091,2016,2154

## Install qycli dev version and stack with "wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE" or the dev version with "wget -qO- qyc.li/i/dev | bash -s cft YOURTOKENHERE"
## or "bash <(wget -qO- qyc.li/inst) v dev k no phpv 7.4"

[ -f /bin/qyc ] && echo "qycli is already installed, stopping. Just type qyc to get the help message or go to qycli.org to learn." && exit

echo "Installing qycli."
echo

if [ "$cloudflare_token" = "" ]; then
    echo "You need to supply a Clouflare API token with the permission template 'Create Additional Tokens'."
    echo "Then you supply it to the qycli installation like this: wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE"
    echo "qycli only works with Cloudflare. Aborting."
    exit
fi

if [ ! -d /var/qyc ]; then
    mkdir -p /var/qyc/qycli /var/qyc/cloudflare/dns /var/qyc/sites /var/qyc/cache/git /var/qyc/bin
fi

tee /var/qyc/cnf.yaml <<EOF
branch_name: $branch_name
sec_install: $sec_install
php_version: $php_version
cloudflare_token: $cloudflare_token
auto_update: $auto_update
EOF
echo

for preq in wget xz systemd-detect-virt systemctl; do
    if command -v "$preq" >/dev/null; then
        continue
    else
        echo "$preq not found, aborting."
        exit 1
    fi
done

echo "Installing unypkg - https://unypkg.org"
echo
wget -qO- uny.nu/pkg | sh -s

if ! command -v unyp; then
    echo "unypkg installation didn't work. Aborting."
    exit 1
fi

if ! command -v git >/dev/null; then
    unyp install git
    unyp system-install git
fi

git -C /var/qyc/qycli clone -b "$branch_name" https://github.com/HOSTYON/qycli .
git -C /var/qyc clone -b "$branch_name" https://github.com/HOSTYON/qycli-plugin

ln -sfv /var/qyc/qycli/bin/qyc /bin/qyc
chmod 755 /bin/qyc

. /var/qyc/qycli/bin/stk
. /var/qyc/qycli/bin/help
. /var/qyc/qycli/bin/upd

printf "\nqycli (%s) script was installed.\n\n" "$branch_name"

printf "\nInstalling the qycli stack now through unypkg.\n\n"
stk_install

printf "\nGetting Cloudflare data.\n\n"
upd_get_cf_tokens
upd_get_cf_accounts_and_zones

if ! systemd-detect-virt --container --quiet && [ "$kernel_tweaks" = "yes" ]; then
    printf "\nOptimizing kernel configurations. You should restart after the full installation has finished.\n\n"
    . /var/qyc/qycli/ins/kernel
fi

if [ "$sec_install" = "yes" ]; then
    printf "\nSecuring the network. Only SSH and Cloudflare connections will be allowed.\n\n"
    . /var/qyc/qycli/ins/sec_firewall
fi

upd_system_resources_qycli_cnf
printf "\nqycli was installed.\n\n"
