#!/usr/bin/env sh
# shellcheck disable=1091,2016,2154,2034

## Install qycli dev version and stack with "wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE" or the dev version with "wget -qO- qyc.li/i/dev | bash -s cft YOURTOKENHERE"
## or wget -qO- qyc.li/i/stable | bash -s php 8.4,8.3,8.2
## To install without Cloudflare token do the following: wget -qO- qyc.li/i/stable | bash -s no-cft

[ "$(whoami)" != "root" ] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit
[ -f /bin/qyc ] && echo "qycli is already installed, stopping. Just type qyc to get the help message or go to qycli.org to learn." && exit

kernel_tweaks=yes
php_versions=8.4
auto_update=no

while [ "$#" -gt 0 ]; do
    case "$1" in
    k | kernel | tweaks)
        kernel_tweaks="$2"
        shift
        ;;
    php | phpv | php-versions)
        php_versions="$2"
        invalid_versions="$(echo "$php_versions" | tr "," "\n" | grep -v "[7-9]\.[0-9]")"
        if [ "$invalid_versions" != "" ]; then
            for ver in $invalid_versions; do
                echo "$ver is not a valid PHP version."
            done
            echo "Aborting installation due to invalid PHP version(s)."
            exit 1
        fi
        php_versions="$(echo "$php_versions" | tr "," "\n")"
        php_default_version="$(echo "$php_versions" | head -n1)"
        shift
        ;;
    no-cft | no-cloudflare-token)
        no_cloudflare_token=true
        shift
        ;;
    cft | cloudflare-token)
        cloudflare_token="$2"
        shift
        ;;
    cftaz)
        cftaz="$2"
        shift
        ;;
    cftwp)
        cftwp="$2"
        shift
        ;;
    aupd | autoupd | autoupdate)
        auto_update="$2"
        shift
        ;;
    esac
    shift
done

echo "Installing qycli."
echo

if [ "$no_cloudflare_token" != "true" ] && [ "$cloudflare_token" = "" ]; then
    echo "You need to supply a Clouflare User API token (Not an Account Token) with the permission template 'Create Additional Tokens'."
    echo "Then you supply it to the qycli installation like this: wget -qO- qyc.li/i/stable | bash -s cft YOURTOKENHERE"
    echo "qycli only works with Cloudflare. Aborting."
    exit 1
elif [ "$no_cloudflare_token" != "true" ] && [ "$cloudflare_token" != "" ]; then

    if wget --method=get -O- -q \
        --header="Authorization: Bearer $cloudflare_token" \
        --header="Content-Type:application/json" \
        https://api.cloudflare.com/client/v4/user/tokens/verify >/dev/null; then

        echo "Cloudflare User Token verified."
    else
        echo "Needs to be a Cloudflare User Token not an Account Token. Aborting."
        exit 1
    fi

fi

if [ ! -d /var/qyc ]; then
    mkdir -p /var/qyc/cloudflare/dns /var/qyc/cache/git /var/qyc/bin
fi

tee /var/qyc/cnf.yaml <<EOF
branch_name: $branch_name
cloudflare_token: $cloudflare_token
auto_update: $auto_update
php_default_version: $php_default_version
EOF
echo

echo "php_versions:" >>/var/qyc/cnf.yaml
for ver in $php_versions; do
    sed "/php_versions:/a\  - $ver" -i /var/qyc/cnf.yaml
done

for preq in wget xz systemd-detect-virt systemctl; do
    if command -v "$preq" >/dev/null; then
        continue
    else
        echo "$preq not found, aborting."
        exit 1
    fi
done

echo "Installing unypkg - https://unypkg.org"
echo
wget -qO- uny.nu/pkg | sh -s

if ! command -v unyp >/dev/null; then
    echo "unypkg installation didn't work. Aborting."
    exit 1
fi

if ! command -v git >/dev/null; then
    unyp install git
    unyp system-install git
fi

git -C /var/qyc clone -b "$branch_name" https://github.com/HOSTYON/qycli
git -C /var/qyc clone -b "$branch_name" https://github.com/HOSTYON/qycli-plugin

ln -sf /var/qyc/qycli/bin/qyc /bin/qyc
chmod 755 /bin/qyc

. /var/qyc/qycli/bin/stk
. /var/qyc/qycli/bin/help
. /var/qyc/qycli/bin/upd

printf "\nqycli (%s) script was installed.\n\n" "$branch_name"

printf "\nInstalling the qycli stack now through unypkg.\n\n"
stk_install

if [ "$no_cloudflare_token" != "true" ]; then
    printf "\nGetting Cloudflare data.\n\n"
    upd_get_cf_tokens
    upd_get_cf_accounts_and_zones
fi

if ! systemd-detect-virt --container --quiet && [ "$kernel_tweaks" = "yes" ]; then
    printf "\nOptimizing kernel configurations. You should restart after the full installation has finished.\n\n"
    . /var/qyc/qycli/ins/kernel
fi

printf "\nqycli was installed.\n\n"
