#!/usr/bin/env sh
# shellcheck disable=1091,2016,2034

[ "$(whoami)" != "root" ] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

sec_install=no
kernel_tweaks=yes
php_version=8.2
auto_update=no

while [ "$#" -gt 0 ]; do
    case "$1" in
    s | sec | security)
        if [ "$2" = "no" ]; then
            sec_install=yes
        fi
        shift
        ;;
    k | kernel | tweaks)
        if [ "$2" = "no" ]; then
            kernel_tweaks=no
        fi
        shift
        ;;
    php | phpv | php-version)
        php_version=$2
        shift
        ;;
    cft | cloudflare-token)
        cloudflare_token=$2
        shift
        ;;
    aupd | autoupd | autoupdate)
        auto_update=$2
        shift
        ;;
    esac
    shift
done
