#!/usr/bin/env sh
# shellcheck disable=1091,2016,2034

[ "$(whoami)" != "root" ] && echo "qycli has to be installed as root, try 'sudo -i' or 'su -' to become root, then try again." && exit

sec_install=no
kernel_tweaks=yes
php_versions=8.3
auto_update=no

while [ "$#" -gt 0 ]; do
    case "$1" in
    s | sec | security)
        if [ "$2" = "no" ]; then
            sec_install=yes
        fi
        shift
        ;;
    k | kernel | tweaks)
        if [ "$2" = "no" ]; then
            kernel_tweaks=no
        fi
        shift
        ;;
    php | phpv | php-versions)
        php_versions=$2
        invalid_versions="$(echo "$php_versions" | tr "," "\n" | grep -v "[7-9]\.[0-9]")"
        if [ "$invalid_versions" != "" ]; then
            for ver in $invalid_versions; do
                echo "$ver is not a valid PHP version."
            done
            echo "Aborting installation due to invalid PHP version(s)."
            exit 1
        fi
        php_versions="$(echo "$php_versions" | tr "," "\n")"
        php_default_version="$(echo "$php_versions" | head -n1)"
        shift
        ;;
    cft | cloudflare-token)
        cloudflare_token=$2
        shift
        ;;
    aupd | autoupd | autoupdate)
        auto_update=$2
        shift
        ;;
    esac
    shift
done
