#!/usr/bin/env sh
# shellcheck disable=1091,2016,2034

branch_name=stable

# Run installer with options
wget -q https://raw.githubusercontent.com/HOSTYON/qycli/refs/heads/"$branch_name"/ins/inst
. ./inst
rm -f ./inst
