extprocessor lsphpSHORTVER {\
  type                    lsapi\
  address                 uds://run/openlitespeed/lsphpSHORTVER.sock\
  maxConns                50\
  env                     PHP_LSAPI_CHILDREN=1\
  env                     LSAPI_AVOID_FORK=0\
  initTimeout             60\
  retryTimeout            0\
  persistConn             1\
  respBuffer              0\
  autoStart               2\
  path                    LSPHP_PATH\
  runOnStartUp            3\
  backlog                 100
  instances               1
  priority                0
  memSoftLimit            0
  memHardLimit            0
  procSoftLimit           0
  procHardLimit           0
}