virtualhost DOMAIN {\
  vhRoot                  HTDOCS\
  configFile              VHOSTCONF\
  allowSymbolLink         1\
  enableScript            1\
  restrained              0\
  setUIDMode              2\
}
