docRoot                   $VH_ROOT/

index  {
  useServer               0
  indexFiles              index.php
}

scripthandler  {
  add                     lsapi:lsphpSHORTVER php
}

context / {
  location                $VH_ROOT
  allowBrowse             1
  indexFiles              index.php

  rewrite  {
    enable                1
    inherit               1
    rewriteFile           HTDOCS/.htaccess
  }
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}
