# All sites common configuration

include common/static/logging.conf;

# Disable Microcache
set $disable_microcache "yes";

# Development environment forces timestamp revalidation
set $php_admin_overrides "opcache.validate_timestamps=1\nopcache.revalidate_freq=0";
