# All sites common configuration

include common/static/logging.conf;

include fastcgi_params;
include fastcgi_qycli_params;

# OPcache dynamic dev override (Cascades down into all FastCGI blocks)
fastcgi_param PHP_ADMIN_VALUE "opcache.validate_timestamps=1\nopcache.revalidate_freq=0";
