fastcgi_split_path_info ^(.+?\.php)(/.*)$;
try_files $fastcgi_script_name =404;

include fastcgi_params;
include fastcgi_qycli_params;

# FPM dynamic override
if ($php_admin_overrides != "") {
    fastcgi_param PHP_ADMIN_VALUE $php_admin_overrides;
}

# Connection Persistence Upgrades
fastcgi_keep_conn on;

# Symmetrical Buffer Architecture
fastcgi_buffer_size 128k;
fastcgi_buffers 4 256k;
fastcgi_busy_buffers_size 256k;

# MICROCACHE ENGINE EVALUATION
set $final_skip_cache 0;

if ($skip_cache_method) { set $final_skip_cache 1; }
if ($skip_cache_xhr)    { set $final_skip_cache 1; }
if ($skip_cache_uri)    { set $final_skip_cache 1; }
if ($skip_cache_cookie) { set $final_skip_cache 1; }
if ($skip_cache_query)  { set $final_skip_cache 1; }

# Honor explicit site includes bypass rules
if ($disable_microcache = "yes") { set $final_skip_cache 1; }

fastcgi_cache or_fcgi_micro_cache;
fastcgi_cache_key "$scheme$request_method$host$request_uri";

# Valid configurations
fastcgi_cache_valid 200 301 3s;
fastcgi_cache_valid 404 2s;
fastcgi_cache_valid 502 503 2s;

# Herd Immunity & Non-blocking Background Refresh Updates
fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;
fastcgi_cache_background_update on;
fastcgi_cache_lock on;
fastcgi_cache_lock_timeout 4s;

fastcgi_cache_bypass $final_skip_cache;
fastcgi_no_cache $final_skip_cache;

add_header X-Cache-Status $upstream_cache_status;