# All sites common configuration

include common/static/caching.conf;

# Enable Microcache
set $disable_microcache "no";

# Production environment gets no overrides (or default memory tweaks)
set $php_admin_overrides "";
