# All sites common configuration

include common/static/caching.conf;

# Enable Microcache
set $disable_microcache "no";

# Production: Pass a completely harmless dummy override
set $php_admin_overrides "opcache.validate_timestamps=0";
